POST http://localhost:3000/posts
content-type: application/json

{
    "title" : "Viktor12345",
    "postType": "post",
    "slug" : "slug-test-js-6",
    "status":  "draft",
    "content" : "test content",
    "schema" : "{\"sidebarEnabled\": true, \"footerActive\": true}",
    "publishOn": "2024-11-29T07:46:32+0000",
    //"tags": ["nestjs", "typescript"],
    "metaOptions": 
        {
           "metaValue" : "{\"sidebarEnabled\": false, \"footerActive\": true}"
           
        },
    "authorId": 2
    
}