POST http://localhost:3000/posts
content-type: application/json

{
    "title" : "Viktor12345",
    "postType": "post",
    "slug" : "slug-test-js",
    "status":  "draft",
    "schema" : "test",
    "publishOn": "2024-11-29T07:46:32+0000",
    "tags": ["nestjs", "typescript"],
    "metaOptions": [
        {
            "key": "testkey",
            "value" :"testvalue"
        }
    ]
}