GET http://localhost:3000/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0Ijo0LCJlbWFpbCI6InZtYWtrc2ltb3Y4OEBnbWFpbC5jb20iLCJpYXQiOjE3MzQyNjYxNzYsImV4cCI6MTczNDI2OTc3NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.Uof4nIX9-eOvuJbm8pA8pRl08swssd_D7kYti-9PcDk