POST http://localhost:3000/users
content-type: application/json


{
    "firstName" : "Viktor1",
    "lastName" : "Maksimov1",
    "email" : "vmakksimov1@gmail.com",
    "password" : "123456-Aa"
}