GET http://localhost:3000/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJlbWFpbCI6InZtYWtrc2ltb3Z2dkBnbWFpbC5jb20iLCJpYXQiOjE3MzUzMTg5NDYsImV4cCI6MTczNTMyMjU0NiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.TOXVxiAF1Okzfa9j1tzDPdudpmjcH5tLw76f4fvBicU